web:
  build: .
  command: "npm run npm-build"
  tty: true
  ports:
    - "8080:3005"
  volumes:
    - ./src:/var/www/src
    - ./package.json:/var/www/package.json
    - ./Gruntfile.js:/var/www/Gruntfile.js
