version: "2"

services:
  node:
    build: .
    command: "npm run dev"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/opt/app/src
      - ./dist:/opt/app/dist
      - ./index.html:/opt/app/index.html
      - ./data.json:/opt/app/data.json
      - ./images:/opt/app/images
      - ./package.json:/opt/app/package.json
      - ./webpack.config.js:/opt/app/webpack.config.js
